# Config
spring:
     # Spring Application Config
     application:
          name: ms-authentication
     # Spring Cloud Config
     cloud:
          config:
               uri: http://localhost:8888
          
server:
     port: 8000

zuul:
     server: http://localhost
     port: 9061
     url: ${zuul.server}:${zuul.port}

info.app.name: @project.name@
info.app.description: @project.description@
info.app.version: @project.version@

# Call Feign External APIs
microservices:
     msclientmanagementv1: ${zuul.url}/${spring.application.name}/v1/